### ISSUE TITLE
[drawnumber] issues/features

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#2171]
I'm packing a few old issues/request into a single ticket, 1st, let me note this is the exact class for [drawtext] and [drawsymbol] as well, they are just aliases.

- [ ] allow typing negative numbers (see https://github.com/pure-data/pure-data/issues/1489)

- [ ] allow shift+click to drag numbers with fine tuning like number boxes in Pd  (see https://github.com/pure-data/pure-data/issues/1489)

- [ ] allow setting font size and maybe also rescale when changing x/y pixels (see https://github.com/pure-data/pure-data/issues/668) I did a preliminary PR at https://github.com/pure-data/pure-data/pull/1622 and could start over and try to deal with all issues here

**Comment by umlaeute** [comment]
is there any advantage in merging issues?
i personally prefer smaller issues over accumulated ones (as it allows us to tackle them separately if - for whatever reasons - one of them proves harder to implement)

**Comment by porres** [comment]
I now realize the task list makes better sense in a PR that gathers different issues, I can revert things when/if I try to make a PR for it. One way or another, it seemed good to organize the issues in a single ticket.

**Comment by reduzent** [comment]
+1 to "implement -x, -xr -xe for [drawnumber] as well to make it non-editable"

**Comment by reduzent** [comment]
Now, since [drawsymbol] becomes editable, too, it is even more important to have a protection for [drawsymbol] and [drawnumber].

**Comment by porres** [comment]
this was a bad idea, just created new separateissues :)
